<?php $presets["skin11r"] = array (
  'general-content_width' => '1300px',
  'general-layout' => 'wide',
  'general-box_width' => '1280px',
  'general-boxed_bg_color' => '#f8f8f9',
  'general-boxed_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'no-repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-boxed_bg_fixed' => '1',
  'general-bg_color' => '#ffffff',
  'general-bg_opacity' => 100,
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-bg_fixed' => false,
  'general-content_boxes_bg_color' => '#f8f8f9',
  'general-content_boxes_bg_opacity' => 100,
  'general-content_boxes_decoration' => 'none',
  'general-content_boxes_decoration_outline_color' => '#000000',
  'general-content_boxes_decoration_outline_opacity' => 0,
  'dividers-color' => '#adb0b6',
  'dividers-opacity' => 30,
  'general-accent_color_mode' => 'gradient',
  'general-accent_bg_color' => '#5891e8',
  'general-accent_bg_color_gradient' => 
  array (
    0 => '#1ebbf0',
    1 => '#39dfaa',
  ),
  'general-border_radius' => 2,
  'general-slideshow_bullets_style' => 'accent',
  'general-fullscreen_overlay_color_mode' => 'color',
  'general-fullscreen_overlay_color' => '#ffffff',
  'general-fullscreen_overlay_gradient' => 
  array (
    0 => '#2edded',
    1 => '#0084bb',
  ),
  'general-fullscreen_overlay_opacity' => 100,
  'general-spinner_color' => '#c4c4c4',
  'general-spinner_opacity' => 100,
  'general-loader_style' => 'double_circles',
  'general-custom_loader' => '',
  'preset' => 'skin11r',
  'header-layout' => 'inline',
  'header-classic-show_elements' => '1',
  'header-classic-icons_style' => 'bold',
  'header-classic-elements' => 
  array (
    'top_bar_left' => 
    array (
      0 => 'custom_menu',
      1 => 'cart',
    ),
    'top_bar_right' => 
    array (
      0 => 'search',
    ),
    'near_menu_right' => 
    array (
      0 => 'social_icons',
    ),
    'near_logo_right' => 
    array (
      0 => 'phone',
      1 => 'email',
    ),
  ),
  'header-classic-elements-near_menu_right-padding-top' => 0,
  'header-classic-elements-near_menu_right-padding-right' => 0,
  'header-classic-elements-near_menu_right-padding-bottom' => 0,
  'header-classic-elements-near_menu_right-padding-left' => 40,
  'header-classic-elements-near_logo_left-padding-top' => 0,
  'header-classic-elements-near_logo_left-padding-right' => 0,
  'header-classic-elements-near_logo_left-padding-bottom' => 0,
  'header-classic-elements-near_logo_left-padding-left' => 0,
  'header-classic-elements-near_logo_right-padding-top' => 0,
  'header-classic-elements-near_logo_right-padding-right' => 0,
  'header-classic-elements-near_logo_right-padding-bottom' => 0,
  'header-classic-elements-near_logo_right-padding-left' => 0,
  'header-inline-show_elements' => '1',
  'header-inline-icons_style' => 'bold',
  'header-inline-elements' => 
  array (
    'near_menu_right' => 
    array (
      0 => 'cart',
      1 => 'search',
    ),
  ),
  'header-inline-elements-near_menu_right-padding-top' => 0,
  'header-inline-elements-near_menu_right-padding-right' => 0,
  'header-inline-elements-near_menu_right-padding-bottom' => 0,
  'header-inline-elements-near_menu_right-padding-left' => 5,
  'header-split-show_elements' => '1',
  'header-split-icons_style' => 'light',
  'header-split-elements' => 
  array (
    'near_menu_left' => 
    array (
      0 => 'search',
    ),
    'near_menu_right' => 
    array (
      0 => 'cart',
    ),
  ),
  'header-split-elements-near_menu_left-padding-top' => 0,
  'header-split-elements-near_menu_left-padding-right' => 20,
  'header-split-elements-near_menu_left-padding-bottom' => 0,
  'header-split-elements-near_menu_left-padding-left' => 20,
  'header-split-elements-near_menu_right-padding-top' => 0,
  'header-split-elements-near_menu_right-padding-right' => 20,
  'header-split-elements-near_menu_right-padding-bottom' => 0,
  'header-split-elements-near_menu_right-padding-left' => 20,
  'header-side-show_elements' => '1',
  'header-side-icons_style' => 'light',
  'header-side-elements' => 
  array (
    'below_menu' => 
    array (
      0 => 'social_icons',
      1 => 'email',
      2 => 'skype',
    ),
  ),
  'header-side-elements-below_menu-padding-top' => 0,
  'header-side-elements-below_menu-padding-right' => 35,
  'header-side-elements-below_menu-padding-bottom' => 0,
  'header-side-elements-below_menu-padding-left' => 35,
  'header-slide_out-show_elements' => '1',
  'header-slide_out-icons_style' => 'light',
  'header-slide_out-elements' => 
  array (
    'side_top_line' => 
    array (
      0 => 'phone',
      1 => 'email',
      2 => 'skype',
    ),
  ),
  'header-slide_out-elements-top_line-padding-top' => 0,
  'header-slide_out-elements-top_line-padding-right' => 40,
  'header-slide_out-elements-top_line-padding-bottom' => 0,
  'header-slide_out-elements-top_line-padding-left' => 40,
  'header-slide_out-elements-below_menu-padding-top' => 0,
  'header-slide_out-elements-below_menu-padding-right' => 0,
  'header-slide_out-elements-below_menu-padding-bottom' => 0,
  'header-slide_out-elements-below_menu-padding-left' => 0,
  'header-overlay-show_elements' => '1',
  'header-overlay-icons_style' => 'light',
  'header-overlay-elements' => 
  array (
    'side_top_line' => 
    array (
      0 => 'social_icons',
      1 => 'text_area',
      2 => 'phone',
    ),
    'below_menu' => 
    array (
      0 => 'search',
      1 => 'cart',
    ),
  ),
  'header-overlay-elements-top_line-padding-top' => 0,
  'header-overlay-elements-top_line-padding-right' => 40,
  'header-overlay-elements-top_line-padding-bottom' => 0,
  'header-overlay-elements-top_line-padding-left' => 40,
  'header-overlay-elements-below_menu-padding-top' => 0,
  'header-overlay-elements-below_menu-padding-right' => 0,
  'header-overlay-elements-below_menu-padding-bottom' => 0,
  'header-overlay-elements-below_menu-padding-left' => 0,
  'header-classic-logo-position' => 'left',
  'header-classic-menu-position' => 'left',
  'header-classic-menu-margin-top' => 0,
  'header-classic-menu-margin-bottom' => 0,
  'header-classic-height' => 180,
  'header-classic-is_fullwidth' => '0',
  'header-inline-menu-position' => 'center',
  'header-inline-height' => 90,
  'header-inline-is_fullwidth' => '0',
  'header-split-menu-position' => 'outside',
  'header-split-height' => 100,
  'header-split-is_fullwidth' => '0',
  'header-side-position' => 'right',
  'header-side-width' => '300px',
  'header-side-content-width' => '300px',
  'header-side-content-position' => 'center',
  'header-side-content-padding-top' => 50,
  'header-side-content-padding-right' => 0,
  'header-side-content-padding-bottom' => 40,
  'header-side-content-padding-left' => 0,
  'header-side-menu-position' => 'v_top',
  'header-side-logo-position' => 'inside',
  'header-side-menu-padding-top' => 50,
  'header-side-menu-padding-bottom' => 50,
  'header-side-menu-items_alignment' => 'center',
  'header-side-menu-items_link' => 'fullwidth',
  'header-slide_out-layout' => 'menu_icon',
  'header-slide_out-layout-menu_icon-show_floating_logo' => '1',
  'header-slide_out-layout-top_line-height' => 90,
  'header-slide_out-layout-top_line-is_fullwidth' => '1',
  'header-slide_out-layout-top_line-logo-position' => 'left',
  'header-slide_out-layout-side_line-width' => 60,
  'header-slide_out-layout-side_line-position' => 'under',
  'header-slide_out-position' => 'left',
  'header-slide_out-overlay-animation' => 'fade',
  'header-slide_out-width' => '400px',
  'header-slide_out-content-width' => '350px',
  'header-slide_out-content-position' => 'center',
  'header-slide_out-content-padding-top' => 50,
  'header-slide_out-content-padding-right' => 0,
  'header-slide_out-content-padding-bottom' => 50,
  'header-slide_out-content-padding-left' => 0,
  'header-slide_out-menu-position' => 'v_top',
  'header-slide_out-logo-position' => 'fully_inside',
  'header-slide_out-menu-padding-top' => 40,
  'header-slide_out-menu-padding-bottom' => 40,
  'header-slide_out-menu-items_alignment' => 'center',
  'header-slide_out-menu-items_link' => 'fullwidth',
  'header-overlay-layout' => 'menu_icon',
  'header-overlay-layout-menu_icon-show_floating_logo' => '1',
  'header-overlay-layout-top_line-height' => 130,
  'header-overlay-layout-top_line-is_fullwidth' => '0',
  'header-overlay-layout-top_line-logo-position' => 'left',
  'header-overlay-layout-side_line-width' => 60,
  'header-overlay-content-width' => '300px',
  'header-overlay-content-position' => 'center',
  'header-overlay-content-padding-top' => 0,
  'header-overlay-content-padding-right' => 0,
  'header-overlay-content-padding-bottom' => 0,
  'header-overlay-content-padding-left' => 0,
  'header-overlay-menu-position' => 'v_center',
  'header-overlay-logo-position' => 'fully_inside',
  'header-overlay-menu-padding-top' => 40,
  'header-overlay-menu-padding-bottom' => 40,
  'header-overlay-menu-items_alignment' => 'center',
  'header-overlay-menu-items_link' => 'fullwidth',
  'top_bar-font-family' => 'Roboto:500',
  'top_bar-font-size' => 13,
  'top_bar-font-is_capitalized' => false,
  'top_bar-font-color' => '#adb0b6',
  'top_bar-paddings-top' => 5,
  'top_bar-paddings-bottom' => 5,
  'top_bar-paddings-horizontal' => 0,
  'top_bar-bg-style' => 'fullwidth_line',
  'top_bar-bg-color' => '#adb0b6',
  'top_bar-bg-opacity' => 30,
  'top_bar-bg-image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg-color' => '#ffffff',
  'header-bg-opacity' => 100,
  'header-bg-image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'header-bg-is_fullscreen' => false,
  'header-bg-is_fixed' => false,
  'header-decoration' => 'line',
  'header-decoration-color' => '#adb0b6',
  'header-decoration-opacity' => 30,
  'header-classic-menu-bg-style' => 'solid',
  'header-classic-menu-bg-color' => '#000000',
  'header-classic-menu-bg-opacity' => 100,
  'header-menu_icon-size' => 'medium',
  'header-menu_icon-color' => '#000000',
  'header-menu_icon-bg-color' => '#ffffff',
  'header-menu_icon-bg-opacity' => 75,
  'header-menu_icon-hover-color' => '#000000',
  'header-menu_icon-hover-bg-color' => '#ffffff',
  'header-menu_icon-hover-bg-opacity' => 75,
  'header-menu_icon-margin-top' => 0,
  'header-menu_icon-margin-right' => 0,
  'header-menu_icon-margin-bottom' => 0,
  'header-menu_icon-margin-left' => 0,
  'header-menu_icon-bg-size' => 54,
  'header-menu_icon-bg-border-radius' => 0,
  'header-mixed-decoration' => 'shadow',
  'header-mixed-decoration-color' => '#dd9933',
  'header-mixed-decoration-opacity' => 100,
  'header-mixed-bg-color' => '#ffffff',
  'header-mixed-bg-opacity' => 100,
  'header-slide_out-overlay-bg-color-style' => 'color',
  'header-slide_out-overlay-bg-color' => '#111111',
  'header-slide_out-overlay-bg-gradient' => 
  array (
    0 => '#cdb7e2',
    1 => '#821482',
  ),
  'header-slide_out-overlay-bg-opacity' => 40,
  'header-slide_out-overlay-blur' => '0',
  'header-slide_out-overlay-x_cursor' => '1',
  'header-slide_out-overlay-x_cursor-color' => '#ffffff',
  'header-slide_out-overlay-x_cursor-opacity' => 100,
  'header-menu-font-family' => 'Roboto:700',
  'header-menu-font-size' => 16,
  'header-menu-font-is_capitalized' => false,
  'header-menu-subtitle-font-family' => 'Arial:400italic',
  'header-menu-subtitle-font-size' => 11,
  'header-menu-font-color' => '#3b3f4a',
  'header-menu-hover-font-color-style' => 'color',
  'header-menu-hover-font-color' => '#3b3f4a',
  'header-menu-hover-font-gradient' => 
  array (
    0 => '#8224e3',
    1 => '#751257',
  ),
  'header-menu-active_item-font-color-style' => 'color',
  'header-menu-active_item-font-color' => '#3b3f4a',
  'header-menu-active_item-font-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-menu-icon-size' => 14,
  'header-menu-show_next_lvl_icons' => false,
  'header-menu-item-padding-top' => 4,
  'header-menu-item-padding-right' => 4,
  'header-menu-item-padding-bottom' => 4,
  'header-menu-item-padding-left' => 4,
  'header-menu-item-margin-top' => 15,
  'header-menu-item-margin-right' => 14,
  'header-menu-item-margin-bottom' => 15,
  'header-menu-item-margin-left' => 14,
  'header-menu-item-surround_margins-style' => 'disabled',
  'header-menu-item-surround_margins-custom-margin' => 30,
  'header-menu-decoration-other-links-is_justified' => '1',
  'header-menu-show_dividers' => '0',
  'header-menu-dividers-height-style' => 'custom',
  'header-menu-dividers-height' => 24,
  'header-menu-dividers-surround' => '0',
  'header-menu-dividers-color' => '#111111',
  'header-menu-dividers-opacity' => 14,
  'header-menu-decoration-style' => 'underline',
  'header-menu-decoration-underline-direction' => 'left_to_right',
  'header-menu-decoration-underline-color-style' => 'accent',
  'header-menu-decoration-underline-color' => '#1e73be',
  'header-menu-decoration-underline-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-menu-decoration-underline-line_size' => '2',
  'header-menu-decoration-other-hover-style' => 'background',
  'header-menu-decoration-other-hover-color-style' => 'accent',
  'header-menu-decoration-other-hover-color' => '#ffffff',
  'header-menu-decoration-other-hover-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-menu-decoration-other-opacity' => 15,
  'header-menu-decoration-other-hover-line' => '0',
  'header-menu-decoration-other-hover-line-color-style' => 'gradient',
  'header-menu-decoration-other-hover-line-color' => '#dd3333',
  'header-menu-decoration-other-hover-line-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-menu-decoration-other-hover-line-opacity' => 23,
  'header-menu-decoration-other-active-style' => 'background',
  'header-menu-decoration-other-active-color-style' => 'accent',
  'header-menu-decoration-other-active-color' => '#ffffff',
  'header-menu-decoration-other-active-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-menu-decoration-other-active-opacity' => 15,
  'header-menu-decoration-other-active-line' => '0',
  'header-menu-decoration-other-active-line-color-style' => 'color',
  'header-menu-decoration-other-active-line-color' => '#8224e3',
  'header-menu-decoration-other-active-line-gradient' => 
  array (
    0 => '#dd3333',
    1 => '#81d742',
  ),
  'header-menu-decoration-other-active-line-opacity' => 30,
  'header-menu-decoration-other-click_decor' => '1',
  'header-menu-decoration-other-click_decor-color-style' => 'accent',
  'header-menu-decoration-other-click_decor-color' => '#ffffff',
  'header-menu-decoration-other-click_decor-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-menu-decoration-other-click_decor-opacity' => 20,
  'header-menu-decoration-other-border-radius' => 3,
  'header-menu-decoration-other-line_size' => '2',
  'header-menu-submenu-font-family' => 'Roboto:500',
  'header-menu-submenu-font-size' => 13,
  'header-menu-submenu-font-is_uppercase' => false,
  'header-menu-submenu-subtitle-font-family' => 'Arial:400italic',
  'header-menu-submenu-subtitle-font-size' => 10,
  'header-menu-submenu-font-color' => '#ffffff',
  'header-menu-submenu-hover-font-color-style' => 'accent',
  'header-menu-submenu-hover-font-color' => '#895cb8',
  'header-menu-submenu-hover-font-gradient' => 
  array (
    0 => '#81d742',
    1 => '#eeee22',
  ),
  'header-menu-submenu-active-font-color-style' => 'accent',
  'header-menu-submenu-active-font-color' => '#ffffff',
  'header-menu-submenu-active-font-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-menu-submenu-icon-size' => 14,
  'header-menu-submenu-show_next_lvl_icons' => '1',
  'header-menu-submenu-item-padding-top' => 8,
  'header-menu-submenu-item-padding-right' => 10,
  'header-menu-submenu-item-padding-bottom' => 8,
  'header-menu-submenu-item-padding-left' => 10,
  'header-menu-submenu-item-margin-top' => 0,
  'header-menu-submenu-item-margin-right' => 0,
  'header-menu-submenu-item-margin-bottom' => 0,
  'header-menu-submenu-item-margin-left' => 0,
  'header-menu-submenu-bg-color' => '#23262d',
  'header-menu-submenu-bg-opacity' => 100,
  'header-menu-submenu-bg-width' => 280,
  'header-menu-submenu-bg-hover' => 'background',
  'header-side-menu-submenu-position' => 'down',
  'header-elements-near_menu-font_family' => 'Roboto:500',
  'header-elements-near_menu-font_size' => 13,
  'header-elements-near_menu-font_color' => '#3b3f4a',
  'header-elements-near_logo-font_family' => 'Open Sans:600',
  'header-elements-near_logo-font_size' => 14,
  'header-elements-near_logo-font_color' => '#393940',
  'header-elements-search-caption' => '',
  'header-elements-search-icon' => '1',
  'header-elements-search-on-desktops' => 'show',
  'header-elements-search-first-header-switch' => 'near_logo',
  'header-elements-search-second-header-switch' => 'near_logo',
  'header-elements-contact-address-caption' => '8500 Beverly Boulevard Los Angeles, CA 90048',
  'header-elements-contact-address-icon' => '1',
  'header-elements-contact-address-on-desktops' => 'show',
  'header-elements-contact-address-first-header-switch' => 'near_logo',
  'header-elements-contact-address-second-header-switch' => 'in_menu',
  'header-elements-contact-phone-caption' => '011 322 44 56',
  'header-elements-contact-phone-icon' => '1',
  'header-elements-contact-phone-on-desktops' => 'show',
  'header-elements-contact-phone-first-header-switch' => 'near_logo',
  'header-elements-contact-phone-second-header-switch' => 'in_menu',
  'header-elements-contact-email-caption' => 'sales@yoursite.com',
  'header-elements-contact-email-icon' => '1',
  'header-elements-contact-email-on-desktops' => 'show',
  'header-elements-contact-email-first-header-switch' => 'near_logo',
  'header-elements-contact-email-second-header-switch' => 'in_menu',
  'header-elements-contact-skype-caption' => 'Your_Skype',
  'header-elements-contact-skype-icon' => '1',
  'header-elements-contact-skype-on-desktops' => 'show',
  'header-elements-contact-skype-first-header-switch' => 'near_logo',
  'header-elements-contact-skype-second-header-switch' => 'in_menu',
  'header-elements-contact-clock-caption' => 'Monday – Friday 10 AM – 8 PM',
  'header-elements-contact-clock-icon' => '1',
  'header-elements-contact-clock-on-desktops' => 'show',
  'header-elements-contact-clock-first-header-switch' => 'near_logo',
  'header-elements-contact-clock-second-header-switch' => 'in_menu',
  'header-elements-login-caption' => 'Login',
  'header-elements-logout-caption' => 'Logout',
  'header-elements-login-icon' => '1',
  'header-elements-login-on-desktops' => 'show',
  'header-elements-login-first-header-switch' => 'near_logo',
  'header-elements-login-second-header-switch' => 'in_menu',
  'header-elements-login-url' => 'http://themeforest.net',
  'header-elements-text-on-desktops' => 'show',
  'header-elements-text-first-header-switch' => 'near_logo',
  'header-elements-text-second-header-switch' => 'in_menu',
  'header-elements-text' => 'Some call to action text goes here!',
  'header-elements-text-2-on-desktops' => 'show',
  'header-elements-text-2-first-header-switch' => 'near_logo',
  'header-elements-text-2-second-header-switch' => 'in_menu',
  'header-elements-text-2' => 'Some call to action text goes here!',
  'header-elements-text-3-on-desktops' => 'show',
  'header-elements-text-3-first-header-switch' => 'near_logo',
  'header-elements-text-3-second-header-switch' => 'in_menu',
  'header-elements-text-3' => 'Some call to action text goes here!',
  'header-elements-menu-on-desktops' => 'show',
  'header-elements-menu-first-header-switch' => 'near_logo',
  'header-elements-menu-second-header-switch' => 'hidden',
  'header-elements-menu-style' => 'list',
  'header-elements-soc_icons-on-desktops' => 'show',
  'header-elements-soc_icons-first-header-switch' => 'near_logo',
  'header-elements-soc_icons-second-header-switch' => 'in_menu',
  'header-elements-soc_icons-color' => '#adb0b6',
  'header-elements-soc_icons-bg' => 'color',
  'header-elements-soc_icons-bg-color' => '#adb0b6',
  'header-elements-soc_icons-bg-opacity' => 17,
  'header-elements-soc_icons-bg-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-elements-soc_icons-hover-color' => '#ffffff',
  'header-elements-soc_icons-hover-bg' => 'accent',
  'header-elements-soc_icons-hover-bg-color' => '#15bfe6',
  'header-elements-soc_icons-bg-hover-opacity' => 100,
  'header-elements-soc_icons-hover-bg-gradient' => 
  array (
    0 => '#ffffff',
    1 => '#000000',
  ),
  'header-elements-soc_icons' => 
  array (
    0 => 
    array (
      'icon' => 'facebook',
      'url' => '',
    ),
    1 => 
    array (
      'icon' => 'facebook',
      'url' => '/',
    ),
    2 => 
    array (
      'icon' => 'twitter',
      'url' => '/',
    ),
    3 => 
    array (
      'icon' => 'google',
      'url' => '/',
    ),
    4 => 
    array (
      'icon' => 'dribbble',
      'url' => '/',
    ),
  ),
  'header-show_floating_navigation' => '1',
  'header-floating_navigation-style' => 'fade',
  'header-floating_navigation-show_after' => 94,
  'header-floating_navigation-height' => 56,
  'header-floating_navigation-bg-color' => '#ffffff',
  'header-floating_navigation-bg-opacity' => 100,
  'header-floating_navigation-decoration' => 'line',
  'header-floating_navigation-decoration-color' => '#adb0b6',
  'header-floating_navigation-decoration-opacity' => 30,
  'header-mobile-first_switch-after' => 990,
  'header-mobile-first_switch-layout' => 'right_left',
  'header-mobile-first_switch-height' => 70,
  'header-mobile-second_switch-after' => 500,
  'header-mobile-second_switch-layout' => 'right_left',
  'header-mobile-second_switch-height' => 56,
  'header-mobile-floating_navigation' => 'menu_icon',
  'header-mobile-menu-font-family' => 'Roboto:700',
  'header-mobile-menu-font-size' => 16,
  'header-mobile-menu-font-is_capitalized' => false,
  'header-mobile-submenu-font-family' => 'Roboto:500',
  'header-mobile-submenu-font-size' => 13,
  'header-mobile-submenu-font-is_capitalized' => false,
  'header-mobile-menu-font-color' => '#3b3f4a',
  'header-mobile-menu-font-hover-color-style' => 'accent',
  'header-mobile-menu-font-hover-color' => '#3c3e45',
  'header-mobile-menu-font-hover-gradient' => 
  array (
    0 => '#b78ce2',
    1 => '#1e73be',
  ),
  'header-mobile-menu-bg-color' => '#ffffff',
  'header-mobile-menu-bg-opacity' => 100,
  'header-mobile-menu-bg-width' => 330,
  'header-mobile-menu-align' => 'right',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin11r.header-logo-regular.png?w=57&h=57',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin11r.header-logo-hd.png?w=114&h=114',
    1 => 0,
  ),
  'header-logo-padding-top' => '0',
  'header-logo-padding-right' => '5',
  'header-logo-padding-bottom' => '0',
  'header-logo-padding-left' => '0',
  'header-style-transparent-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin11r.header-style-transparent-logo-regular.png?w=57&h=57',
    1 => 0,
  ),
  'header-style-transparent-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin11r.header-style-transparent-logo-hd.png?w=114&h=114',
    1 => 0,
  ),
  'header-style-transparent-logo-padding-top' => '0',
  'header-style-transparent-logo-padding-right' => '5',
  'header-style-transparent-logo-padding-bottom' => '0',
  'header-style-transparent-logo-padding-left' => '0',
  'header-style-mixed-logo_regular' => 
  array (
    0 => '',
    1 => 0,
  ),
  'header-style-mixed-logo_hd' => 
  array (
    0 => '',
    1 => 0,
  ),
  'header-style-mixed-logo-padding-top' => '0',
  'header-style-mixed-logo-padding-right' => '0',
  'header-style-mixed-logo-padding-bottom' => '0',
  'header-style-mixed-logo-padding-left' => '0',
  'header-style-floating-choose_logo' => 'custom',
  'header-style-floating-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin11r.header-style-floating-logo-regular.png?w=44&h=44',
    1 => 0,
  ),
  'header-style-floating-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin11r.header-style-floating-logo-hd.png?w=88&h=88',
    1 => 0,
  ),
  'header-style-floating-logo-padding-top' => '0',
  'header-style-floating-logo-padding-right' => '18',
  'header-style-floating-logo-padding-bottom' => '0',
  'header-style-floating-logo-padding-left' => '0',
  'header-mobile-first_switch-logo' => 'desktop',
  'header-mobile-second_switch-logo' => 'mobile',
  'header-style-mobile-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin11r.header-style-mobile-logo-regular.png?w=44&h=44',
    1 => 0,
  ),
  'header-style-mobile-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin11r.header-style-mobile-logo-hd.png?w=88&h=88',
    1 => 0,
  ),
  'header-style-mobile-logo-padding-top' => '0',
  'header-style-mobile-logo-padding-right' => '0',
  'header-style-mobile-logo-padding-bottom' => '0',
  'header-style-mobile-logo-padding-left' => '0',
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin11r.bottom-bar-logo-regular.png?w=28&h=28',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin11r.bottom-bar-logo-hd.png?w=56&h=56',
    1 => 0,
  ),
  'bottom_bar-logo-padding-top' => '8',
  'bottom_bar-logo-padding-right' => '12',
  'bottom_bar-logo-padding-bottom' => '8',
  'bottom_bar-logo-padding-left' => '0',
  'bottom_bar-credits' => '1',
  'stripes-stripe_1_color' => '#f8f8f9',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_outline' => 'hide',
  'stripes-stripe_1_outline_color' => '#44bb70',
  'stripes-stripe_1_outline_opacity' => 100,
  'stripes-stripe_1_content_boxes_bg_color' => '#ffffff',
  'stripes-stripe_1_content_boxes_bg_opacity' => 100,
  'stripes-stripe_1_content_boxes_decoration' => 'none',
  'stripes-stripe_1_content_boxes_decoration_outline_color' => '#dd3333',
  'stripes-stripe_1_content_boxes_decoration_outline_opacity' => 100,
  'stripes-stripe_1_headers_color' => '#3b3f4a',
  'stripes-stripe_1_text_color' => '#787d85',
  'stripes-stripe_2_color' => '#23262d',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_outline' => 'hide',
  'stripes-stripe_2_outline_color' => '#ffffff',
  'stripes-stripe_2_outline_opacity' => 15,
  'stripes-stripe_2_content_boxes_bg_color' => '#ffffff',
  'stripes-stripe_2_content_boxes_bg_opacity' => 10,
  'stripes-stripe_2_content_boxes_decoration' => 'none',
  'stripes-stripe_2_content_boxes_decoration_outline_color' => '#ffffff',
  'stripes-stripe_2_content_boxes_decoration_outline_opacity' => 15,
  'stripes-stripe_2_headers_color' => '#ffffff',
  'stripes-stripe_2_text_color' => '#8b9199',
  'stripes-stripe_3_color' => '#000000',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin22.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_outline' => 'hide',
  'stripes-stripe_3_outline_color' => '#252728',
  'stripes-stripe_3_outline_opacity' => 100,
  'stripes-stripe_3_content_boxes_bg_color' => '#ffffff',
  'stripes-stripe_3_content_boxes_bg_opacity' => 10,
  'stripes-stripe_3_content_boxes_decoration' => 'none',
  'stripes-stripe_3_content_boxes_decoration_outline_color' => '#ffffff',
  'stripes-stripe_3_content_boxes_decoration_outline_opacity' => 19,
  'stripes-stripe_3_headers_color' => '#ffffff',
  'stripes-stripe_3_text_color' => '#ffffff',
  'sidebar-width' => '340px',
  'sidebar-vertical_distance' => 50,
  'sidebar-visual_style' => 'with_dividers',
  'sidebar-divider-vertical' => '1',
  'sidebar-divider-horizontal' => '0',
  'sidebar-bg_color' => '#f8f8f9',
  'sidebar-bg_opacity' => 100,
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-decoration' => 'none',
  'sidebar-decoration_outline_color' => '#000000',
  'sidebar-decoration_outline_opacity' => 6,
  'sidebar-headers_color' => '#3b3f4a',
  'sidebar-primary_text_color' => '#787d85',
  'footer-style' => 'solid_background',
  'footer-bg_color' => '#23262d',
  'footer-bg_opacity' => 100,
  'footer-decoration' => 'none',
  'footer-decoration_outline_color' => '#81d742',
  'footer-decoration_outline_opacity' => 96,
  'footer-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-slide-out-mode' => '0',
  'footer-headers_color' => '#ffffff',
  'footer-primary_text_color' => '#9aa0a7',
  'footer-padding-top' => 50,
  'footer-padding-bottom' => 15,
  'footer-paddings-columns' => 25,
  'footer-collapse_after' => 768,
  'bottom_bar-enabled' => '1',
  'bottom_bar-style' => 'content_width_line',
  'bottom_bar-bg_color' => '#ffffff',
  'bottom_bar-bg_opacity' => 13,
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#ffffff',
  'general-filter_style' => 'minimal',
  'general-filter_style-minimal-border_radius' => 100,
  'general-filter_style-material-line_size' => 2,
  'general-filter-font-family' => 'Roboto:700',
  'general-filter-font-size' => 14,
  'general-filter_ucase' => false,
  'general-filter-padding-top' => 6,
  'general-filter-padding-right' => 15,
  'general-filter-padding-bottom' => 6,
  'general-filter-padding-left' => 15,
  'general-filter-margin-top' => 0,
  'general-filter-margin-right' => 3,
  'general-filter-margin-bottom' => 0,
  'general-filter-margin-left' => 3,
  'general-navigation_margin' => 40,
  'blog-fancy_date-style' => 'circle',
  'post-show_fancy_date' => '1',
  'post-show_fancy_categories' => '1',
  'blog-thumbnail_size' => 'resize',
  'blog-thumbnail_proportions' => 
  array (
    'width' => 2,
    'height' => 1,
  ),
  'general-show_rel_posts' => '1',
  'general-rel_posts_head_title' => 'Related Posts',
  'general-rel_posts_max' => 6,
  'general-title_align' => 'center',
  'general-title_height' => 200,
  'page_title-padding-top' => 0,
  'page_title-padding-bottom' => 0,
  'general-show_titles' => '1',
  'general-title_size' => 'h2',
  'general-title_color' => '#3b3f4a',
  'general-show_breadcrumbs' => '1',
  'general-breadcrumbs_color' => '#adb0b6',
  'general-breadcrumbs_bg_color' => 'disabled',
  'general-title_bg_mode' => 'background',
  'header-background' => 'normal',
  'header-transparent_bg_color' => '#eeee22',
  'header-transparent_bg_opacity' => 100,
  'page_title-background-style-transparent-color_scheme' => 'light',
  'general-title_bg_color' => '#f8f8f9',
  'general-title_bg_opacity' => 100,
  'general-title_decoration' => 'none',
  'general-title_decoration_outline_color' => '#1e73be',
  'general-title_decoration_outline_opacity' => 0,
  'general-title_bg_gradient' => 
  array (
    0 => '#4a66d6',
    1 => '#12b4ea',
  ),
  'general-title_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'general-title_bg_fullscreen' => false,
  'general-title_bg_fixed' => false,
  'general-title_bg_parallax' => '0',
  'content-headers_color' => '#3b3f4a',
  'content-primary_text_color' => '#787d85',
  'content-secondary_text_color' => '#adb0b6',
  'fonts-font_family' => 'Open Sans',
  'fonts-big_size' => 15,
  'fonts-big_size_line_height' => 28,
  'fonts-normal_size' => 14,
  'fonts-normal_size_line_height' => 26,
  'fonts-small_size' => 13,
  'fonts-small_size_line_height' => 25,
  'fonts-h1_font_family' => 'Roboto',
  'fonts-h1_font_size' => 52,
  'fonts-h1_line_height' => 62,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'Roboto:500',
  'fonts-h2_font_size' => 34,
  'fonts-h2_line_height' => 44,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Roboto:500',
  'fonts-h3_font_size' => 25,
  'fonts-h3_line_height' => 36,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Roboto:700',
  'fonts-h4_font_size' => 20,
  'fonts-h4_line_height' => 30,
  'fonts-h4_uppercase' => false,
  'fonts-h5_font_family' => 'Roboto:700',
  'fonts-h5_font_size' => 16,
  'fonts-h5_line_height' => 28,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Roboto:700',
  'fonts-h6_font_size' => 14,
  'fonts-h6_line_height' => 26,
  'fonts-h6_uppercase' => false,
  'buttons-style' => 'material',
  'buttons-color_mode' => 'accent',
  'buttons-color' => '#81d742',
  'buttons-color_gradient' => 
  array (
    0 => '#13aa4a',
    1 => '#84df31',
  ),
  'buttons-hover_color_mode' => 'accent',
  'buttons-hover_color' => '#81d742',
  'buttons-hover_color_gradient' => 
  array (
    0 => '#68adfa',
    1 => '#9d69f9',
  ),
  'buttons-text_color_mode' => 'color',
  'buttons-text_color' => '#ffffff',
  'buttons-text_hover_color_mode' => 'color',
  'buttons-text_hover_color' => '#ffffff',
  'buttons-s_font_family' => 'Roboto:700',
  'buttons-s_font_size' => 12,
  'buttons-s_uppercase' => false,
  'buttons-s_padding-top' => 8,
  'buttons-s_padding-right' => 12,
  'buttons-s_padding-bottom' => 7,
  'buttons-s_padding-left' => 12,
  'buttons-s_border_radius' => 2,
  'buttons-m_font_family' => 'Roboto:700',
  'buttons-m_font_size' => 14,
  'buttons-m_uppercase' => false,
  'buttons-m_padding-top' => 11,
  'buttons-m_padding-right' => 18,
  'buttons-m_padding-bottom' => 10,
  'buttons-m_padding-left' => 16,
  'buttons-m_border_radius' => 2,
  'buttons-l_font_family' => 'Roboto:700',
  'buttons-l_font_size' => 18,
  'buttons-l_uppercase' => false,
  'buttons-l_padding-top' => 17,
  'buttons-l_padding-right' => 24,
  'buttons-l_padding-bottom' => 16,
  'buttons-l_padding-left' => 24,
  'buttons-l_border_radius' => 2,
  'input_height' => 38,
  'input_border_radius' => 1,
  'input_color' => '#787d85',
  'input_border_color' => '#adb0b6',
  'input_border_opacity' => 30,
  'input_bg_color' => '#ffffff',
  'input_bg_opacity' => 100,
  'image_hover-style' => 'none',
  'image_hover-onclick_animation' => false,
  'image_hover-default_icon' => 'none',
  'image_hover-color_mode' => 'accent',
  'image_hover-color' => '#0ca2e0',
  'image_hover-color_gradient' => 
  array (
    0 => '#2edded',
    1 => '#0084bb',
  ),
  'image_hover-opacity' => 36,
  'image_hover-project_icons_style' => 'outline',
  'image_hover-album_miniatures_style' => 'style_2',
  'image_hover-project_rollover_color_mode' => 'accent',
  'image_hover-project_rollover_color' => '#000000',
  'image_hover-project_rollover_color_gradient' => 
  array (
    0 => '#2edded',
    1 => '#0084bb',
  ),
  'image_hover-project_rollover_opacity' => 85,
  'social_buttons-visibility' => 'allways',
  'general-page_content_top_margin' => 70,
  'general-page_content_bottom_margin' => 70,
  'general-responsive' => '1',
  'general-responsiveness-treshold' => 970,
  'general-side_content_paddings' => 50,
  'general-switch_content_paddings' => 778,
  'general-mobile_side_content_paddings' => 20,
  'general-images_lazy_loading' => '1',
  'general-smooth_scroll' => 'off',
  'general-custom_css' => '',
  'header-elements-woocommerce_cart-caption' => '',
  'header-elements-woocommerce_cart-icon' => '1',
  'header-elements-woocommerce_cart-on-desktops' => 'show',
  'header-elements-woocommerce_cart-first-header-switch' => 'near_logo',
  'header-elements-woocommerce_cart-second-header-switch' => 'in_menu',
  'header-elements-woocommerce_cart-show_sub_cart' => '1',
  'header-elements-woocommerce_cart-show_subtotal' => '1',
  'header-elements-woocommerce_cart-show_counter' => 'allways',
  'header-elements-woocommerce_cart-counter-style' => 'round',
  'header-elements-woocommerce_cart-counter-color' => '#ffffff',
  'header-elements-woocommerce_cart-counter-bg' => 'accent',
  'header-elements-woocommerce_cart-counter-bg-color' => '#000000',
  'header-elements-woocommerce_cart-counter-bg-gradient' => 
  array (
    0 => '#37a0fe',
    1 => '#6b5ffd',
  ),
  'general-next_prev_in_album' => '1',
  'general-show_back_button_in_album' => '1',
  'general-album_back_button_target_page_id' => 16237,
  'general-album_meta_on' => '1',
  'general-album_meta_date' => '1',
  'general-album_meta_author' => false,
  'general-album_meta_categories' => '1',
  'general-album_meta_comments' => false,
  'modules-portfolio-status' => 'enabled',
  'modules-testimonials-status' => 'enabled',
  'modules-team-status' => 'enabled',
  'modules-logos-status' => 'enabled',
  'modules-benefits-status' => 'enabled',
  'modules-albums-status' => 'enabled',
  'modules-slideshow-status' => 'enabled',
  'woocommerce_rel_products_max' => 6,
'woocommerce_product_img_width' => '50%',
  'woocommerce_cart_switch' => 990,
  'woocommerce_steps_bg_color' => '#ffffff',
  'woocommerce_steps-bg_opacity' => 0,
  'woocommerce_steps_color' => '#3b3f4a',
  'woocommerce_cart_top_padding' => 70,
  'woocommerce_cart_bottom_padding' => 10,
  'sidebar-distance_to_content' => 50,
  'sidebar-responsiveness' => 990,
  'social_buttons-product-button_title' => 'Share this product',
  'social_buttons-product' => 
  array (
    0 => 'facebook',
    1 => 'google+',
    2 => 'twitter',
    3 => 'linkedin',
    4 => 'pinterest',
  ),
); ?>